"""Contains a class that represents a regular file stored on Google Drive."""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import md5
from structlog import getLogger
from typing import Any

from dateutil import parser as timestamp_parser


import blabgddatalake.remote.file as file
from blabgddatalake.remote.file import RemoteFile

_logger = getLogger(__name__)


@dataclass
class RemoteRegularFile(RemoteFile):
    """Represents a regular file stored on Google Drive.

    Does not include Google Workspace files.
    """

    size: int
    """File size in bytes"""

    md5_checksum: str
    """File hash"""

    head_revision_id: str
    """Current version id (generated by Google Drive)"""

    can_download: bool
    """Whether the file can be downloaded"""

    @property
    def local_name(self) -> str:
        """Local file name (without path).

        Returns:
            Local file name
        """
        return (self.id +
                '_' + (self.head_revision_id or '') +
                '_' + (self.md5_checksum or ''))

    @classmethod
    def _md5(cls, fn: str) -> str:
        md5_hash = md5()
        with open(fn, 'rb') as fd:
            for chunk_4k in iter(lambda: fd.read(4096), b''):
                md5_hash.update(chunk_4k)
        return md5_hash.hexdigest()

    @classmethod
    def from_dict(cls, metadata: dict[str, Any],
                  parent: file.RemoteDirectory | None = None
                  ) -> RemoteRegularFile:
        """Create an instance from a dictionary with data from Google Drive.

        Documentation is available
        `here <https://developers.google.com/drive/api/v3/reference/files>`_.

        Args:
            metadata: a dictionary with file metadata
            parent: the parent directory, if this is not the root

        Returns:
            an instance with the metadata obtained from ``f``

        """
        return RemoteRegularFile(
            metadata['name'], metadata['id'], metadata['mimeType'],
            timestamp_parser.parse(metadata['createdTime']),
            timestamp_parser.parse(metadata['modifiedTime']),
            metadata['lastModifyingUser']['displayName'],
            metadata['webViewLink'], metadata['iconLink'], parent,
            int(s) if (s := metadata.get('size', None)) is not None else 0,
            metadata.get('md5Checksum', None),
            metadata.get('headRevisionId', None),
            metadata.get('capabilities', {}).get('canDownload', False),
        )
