name: Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  all-test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '^3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.2.0a2

      - name: Install dependencies
        run: |
          poetry install --no-interaction --with=test

      - name: Run tests
        run: |
          poetry run python -m unittest
